### ISSUE TITLE
rocm_bandwdith_test can't communicate gpu with gpu

### ISSUE THREAD

**Issue by hyuen** [RadeonOpenCompute/rocm_bandwidth_test#18]
I have a setting where there are 8 CPUs (Intel) and two GPUs, ran the rocm_bandwidth_test, and couldn't measure cross GPU communication

I used rocm 1.9 rpms from http://repo.radeon.com/rocm/misc/facebook/yum/.yum_1.9.white_rabbit/
this is on centos 7.5.1804 with kernel 3.10.0-862.el7.x86_64

**Comment by hyuen** [comment]
I couldn't find the vbios version for the GPU, if you post some instructions on how to do that, I can get that info.

**Comment by rerrabolu** [comment]
Can you post the output of the following commands:

<shell_prompt> ./rocm_bandwidth_test -t
<shell_prompt> lspci -vv -d0x1002:

**Comment by rerrabolu** [comment]
The reason there is no Gpu-to-Gpu data transfer is because there is no path present between the two devices. I suspect the platform has more than one socket with each socket getting one Gpu. On Intel systems it is not possible to communicate across sockets.

Can I get the output of the following commands.

<shell_prompt> lspcu | grep -i numa
<shell_prompt> lspcu | grep -i socket
<shell_prompt> lspcu -p=cpu,core,socket,node

**Comment by rerrabolu** [comment]
I want output of "lscpu" not "lspci". Want to see if the two Gpu's belong to different PCIe domains

**Comment by rerrabolu** [comment]
The data from lscpu command show the system has the following: 8 sockets with each socket having 16 cores where each core has 2 Cpu's.

On Intel system's P2P communication between two Gpu devices that are connected to different Sockets (PCIe Root complexes) is not supported. I have heard of Intel system with dual root that support P2P communication. I will find out the configuration parameters that allow it.

To determine that the installed software supports P2P, I suggest seating the two MI-25 (Vega10) cards in such a manner that they map to the same socket. This will allow P2P testing. The silk printing on the motherboard could be used as a guide to determine which PCIe slots map to which sockets.

**Comment by rerrabolu** [comment]
Could you also indicate what system you have i.e. the motherboard being used. You can run the command "sudo dmidecode" and provide its output for the motherboard (Handle 0x0001 - DMI type 1).

**Comment by hyuen** [comment]
I couldn't find the handle/dmi you suggested, I only found handle 0x0001 DMI type 19

but found this with dmidecode -t 2
Handle 0x00D2, DMI type 2, 17 bytes
Base Board Information
        Manufacturer: HPE
        Product Name: Superdome Flex
        Version: 5
        Serial Number: 5UF82369ZH
        Asset Tag: Base Board Asset Tag
        Features:
                Board is a hosting board
                Board is replaceable
        Location In Chassis: Part Component
        Chassis Handle: 0x0000
        Type: Motherboard
        Contained Object Handles: 0

I am also attaching the whole output of dmidecode

**Comment by hyuen** [comment]
[dmi.txt](https://github.com/RadeonOpenCompute/rocm_bandwidth_test/files/2596392/dmi.txt)

**Comment by rerrabolu** [comment]
Were you able to seat the two Gpu cards so that they map to the same Cpu socket. As I have stated earlier, two Gpus D1 and D2 connected to two Cpu Sockets S1 and S2 will not work. Both devices D1 and D2 must be connected to the same Cpu socket S<i>. The silk-screen print on the motherboard or its manual should guide you as to which PCIe slots you should be using.

**Comment by rerrabolu** [comment]
The dmi.txt file you attached has information on the System. Look around lines: 3918 - 3928.

Handle 0x00D1, DMI type 1, 27 bytes
System Information
	Manufacturer: HPE
	Product Name: Superdome Flex
	Version: IP147
	Serial Number: 5UF82369ZH
	UUID: 98CDFAD1-F6E7-5330-A112-AE5161A857F4
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: HPEMCS03020101

**Comment by rerrabolu** [comment]
Please close the ticket if there are no other concerns.
