### ISSUE TITLE
Incorrect (missing) dependencies in deb package

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/rocm_bandwidth_test#21]
```
# apt-cache show rocm_bandwidth_test | egrep 'Package|Depend'
Package: rocm_bandwidth_test
#
```

```
# /opt/rocm/bin/rocm_bandwidth_test 
/opt/rocm/bin/rocm_bandwidth_test: error while loading shared libraries: libhsa-runtime64.so.1: cannot open shared object file: No such file or directory
#
```

```
# ldd /opt/rocm/bin/rocm_bandwidth_test 
	linux-vdso.so.1 (0x00007ffc26c1d000)
	libhsa-runtime64.so.1 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f89df647000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f89df63d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f89df4a9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f89df2ec000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f89df2d2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f89df7f3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f89df2af000)
```

Indicates it should depend on `libc6`, `libstdc++6`, `libgcc1` and `hsakmt-roct-dev`.

**Comment by rerrabolu** [comment]
Hi, did not see this until this morning. Apologize for the very late response.

Are you saying that rocm_bandwidth_test should express the dependency on those libraries. I can understand the ask that **apt-cache show rocm_bandwidth_test | egrep 'Package|Depend'** should show hsa-rocr-dev

With regards to others, are they not standard libraries on a Ubuntu system ?

Could you describe what you are suggesting in more detail ?

**Comment by baryluk** [comment]
According to Debian packaging manual, aka Debian policy, chapter 3.5:


https://www.debian.org/doc/debian-policy/ch-binary.html#dependencies

"Every package must specify the dependency information about other packages
that are required for the first to work correctly.

For example, a dependency entry must be provided for any shared libraries
required by a dynamically-linked executable binary in a package."

"Packages are not required to declare any dependencies they have on other
packages which are marked Essential (see below), and should not do so
unless they depend on a particular version of that package."

libc6 and libgcc1 are not essential. This should be explicitly mentioned in
Dependencies.

The packages mentioned in the original bug report should be included in
Depends.

**Comment by rerrabolu** [comment]
Wondering where you got the package name "**hsakmt-roct-dev**"

I pushed a change where you will see the debian show that it needs two packages:  hsa-rocr-dev and libstdc++6. Including below the output from apt command.

Depends: libstdc++6, hsa-rocr-dev

**Comment by rerrabolu** [comment]
Could you let me know once you have had chance to inspect the updated build.

**Comment by baryluk** [comment]
Hi rerrabolu.

Yes, the updated rules now look perfect!

It is indeed sufficient to add libstdc++6 and hsa-rocr-dev. I must have
made a mistake (typo or copy/paste from other bug) in original issue
report. That is all.

Thank you.

Can be closed.

**Comment by rerrabolu** [comment]
Thanks for taking time in pointing out the issue. Appreciate it very much.
