### ISSUE TITLE
rocm_bandwidth_test deb package should not use underscores.

### ISSUE THREAD

**Issue by baryluk** [RadeonOpenCompute/rocm_bandwidth_test#22]
It is somehow a bad practice in Debian packaging world to use underscores in package names and package file names.

Consider `rocm-bandwidthtest`

**Comment by Bengt** [comment]
Yes, underscores in the command name are surprising. This makes ROCm's bandwidth test feel out of place on a Linux system. The underscores also break auto completion if users assume a hyphen and hit tab on `rocm-`. Since "bandwidthtest" is not a proper english word, I would suggest a second hyphen: `rocm-bandwidth-test`

**Comment by Bengt** [comment]
@rerrabolu What is the solution to this issue? Have you changed the name or have you considered renaming, but decided against it?

**Comment by rerrabolu** [comment]
I sincerely apologize for not updating the ticket. The name was changed to suggested name: rocm-bandwidth-test. The changed was made nearly year plus ago. Including here the updated names of exe, and its DEB and RPM packages

**- rwxrwxr-x 1 user1 user1 1098600 Jun  8 17:48 rocm-bandwidth-test*
- rw-rw-r-- 1 user1 user1  373952 Jun  8 17:48 rocm-bandwidth-test_1.4.0.99999-local_amd64.deb
- rw-rw-r-- 1 user1 user1  378931 Jun  8 17:48 rocm-bandwidth-test-1.4.0.99999-local.x86_64.rpm**

Let me know if this resolves the issue or not.

**Comment by Bengt** [comment]
@rerrabolu Never mind only updating this ticket now. Awesome that the name was changed to for the better in the past. Thanks for coming back with an explanation. I can confirm that the package and the executable name are now nicer:

```
$ sudo apt install rocm-bandwidth-test
[...]
$ /opt/rocm/bin/rocm-bandwidth-test
................
          RocmBandwidthTest Version: 2.5.1

          Launch Command is: /opt/rocm/bin/rocm-bandwidth-test (rocm_bandwidth -a + rocm_bandwidth -A)


          Device: 0,  AMD Ryzen Threadripper 1950X 16-Core Processor
          Device: 1,  Vega 10 XL/XT [Radeon RX Vega 56/64],  GPU-02151de3936c4944,  0b:0.0
          Device: 2,  Vega 10 XL/XT [Radeon RX Vega 56/64],  GPU-0213f260e1523984,  45:0.0

          Inter-Device Access

          D/D       0         1         2         

          0         1         0         0         

          1         1         1         0         

          2         1         0         1         


          Inter-Device Numa Distance

          D/D       0         1         2         

          0         0         N/A       N/A       

          1         20        0         N/A       

          2         20        N/A       0         


          Unidirectional copy peak bandwidth GB/s

          D/D       0           1           2           

          0         N/A         9.590       9.590       

          1         9.027       72.591      N/A         

          2         9.026       N/A         69.220      


          Bidirectional copy peak bandwidth GB/s

          D/D       0           1           2           

          0         N/A         14.493      14.448      

          1         14.493      N/A         N/A         

          2         14.448      N/A         N/A         
```
