### ISSUE TITLE
Infinity Fabric for GPU-GPU data transfers?

### ISSUE THREAD

**Issue by vvsteg** [RadeonOpenCompute/rocm_bandwidth_test#58]
There is no call of `hipDeviceEnablePeerAccess` in this benchmark. Does it mean that with the current version there is no possibility to test Infinity Fabric for GPU-GPU data transfers?

**Comment by jlgreathouse** [comment]
This application does not use HIP, it is directly built on top of ROCr's APIs, rather than the higher-level HIP language. If there is a path over Infinity Fabric for peer-to-peer communication, it will use it.
