### ISSUE TITLE
Incorrect path in CMake instructions in Readme.md

### ISSUE THREAD

**Issue by nsburbank** [RadeonOpenCompute/rocm_bandwidth_test#64]
For the two cmake examples, there is an error in the path. 

This should be -DCMAKE_MODULE_PATH="_ABSOLUTE_PATH_TO_RBT/rocm_bandwidth_test/cmake_modules" rather than
-DCMAKE_MODULE_PATH="_ABSOLUTE_PATH_TO_RBT/roc_bandwidth_test/cmake_modules"

**Comment by rerrabolu** [comment]
Hi, thanks for pointing out the issue. I  missed this issue until now.
