### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by catsdogone** [RadeonOpenCompute/rocm_bandwidth_test#7]
rocm_bandwidth_test_topology.cpp:296:63: error: ‘hsa_amd_memory_pool_link_info_t {aka struct hsa_amd_memory_pool_link_info_s}’ has no member named ‘numa_distance’
         link_matrix_[(idx1 *agent_index_) + idx2] = link_info.numa_distance;

**Comment by rerrabolu** [comment]
The code that defines the symbol numa_distance is not yet released publicly. Once it is released this will be fixed. Until such time this will remain a problem. The repo is not yet released to public. I can ensure that the symbol is also available at that point of time.
